[project]
name = "desktop-gui-testing"
version = "0.1.0"
description = "Sample application for testing desktop GUI applications using PyAutoGUI"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.3.0",
    "pyautogui>=0.9.54",
]
